version: '3.4'
name: "actstranglerfig"

services:
  apigateway:
    environment:
      - Services__UniSabana.ApiLibreriaKml__DownstreamPath=http://ApiMigada:8081
      - Services__ApiMonolitica__DownstreamPath=http://ApiMonolitica:8082
    build:
      context: ./ApiGateway
      dockerfile: ./Dockerfile
    container_name: ApiGateway
    ports:
      - "8080:8080"
    networks:
      - mi-red-containers
  apimigrada:
    build:
      context: ./ApiMigrada/UniSabana.ApiLibreriaKml
      dockerfile: ./Dockerfile
    container_name: ApiMigada
    ports:
      - "8081:8081"
    networks:
      - mi-red-containers
networks:
  mi-red-containers:
    name: mi-red-containers
    external: true
